### ISSUE TITLE
Mistake in post-installation boot loader configuration

### ISSUE THREAD

**Issue by cspipaon** [nemanjadjekic/xps9560#1]
First and foremost, thanks for the great guide! Very clear and easy to follow.

Just wanted to point out you missed the correct path for the bootloader options in Part IV. Where you state "Navigate to file _boot/efi/loader.conf_ ...".

The path should be _boot/efi/loader/loader.conf_.

---

In order to make the guide completely newbie friendly, I would recommend you to describe the partition creation process in Linux slightly more in-depth (a sentence or two would suffice; [this link](https://www.fosslinux.com/1064/how-to-create-or-add-a-swap-partition-in-ubuntu-and-linux-mint.htm) helped me as well). 
I would also put the end of the "Long answer: ... " paragraph (i.e. from "So in order to increase EFI partition size..." onwards) in the beginning of the next paragraph. I think the "Long answer: ..." paragraph may be confused with a TL;DR section, however it is a crucial step.

Anyways, these are just my thoughts on how to improve an already excellent guide. Thanks again for taking the effort to create it!

**Comment by nemanjadjekic** [comment]
@cspipaon I just saw this issue and I want to thank you for your suggestions. I will perform these tasks as soon as possible.

Task list:
- [x] Update _boot/efi/loader... path_
- [x] Reformat _**Long, Short answer**_ section
- [x] Make guide completely newbie friendly. Add reference to article how to format disk with Linux step by step.

**Comment by nemanjadjekic** [comment]
Added suggestion to guide.
